import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository, InjectDataSource } from '@nestjs/typeorm';
import { Recipe } from 'src/entities/recipe.entity';
import { Repository, Like, DataSource } from 'typeorm';
import { GetRecipesQueryDto } from './dto/get-recipes-query.dto';
import { Pagination } from 'src/common/interfaces/pagination.interface';
import { RagService } from '../rag/rag.service';

@Injectable()
export class RecipesService {
  private readonly logger = new Logger(RecipesService.name);

  constructor(
    @InjectRepository(Recipe)
    private recipeRepository: Repository<Recipe>,
    @InjectDataSource()
    private dataSource: DataSource,
    private ragService: RagService,
  ) {}

  /**
   * Gets all recipes from the database with optional filtering and pagination
   */
  public async getAllRecipes(
    query: GetRecipesQueryDto,
  ): Promise<Pagination<Recipe>> {
    try {
      const { search, page = 1, limit = 10 } = query;
      const skip = (page - 1) * limit;

      // Build where clause for search
      const where: Record<string, unknown> = {};
      if (search) {
        where.name = Like(`%${search}%`);
      }

      // Get total count for pagination
      const total = await this.recipeRepository.count({ where });

      // Get paginated results
      const data = await this.recipeRepository.find({
        where,
        order: {
          created_at: 'DESC',
        },
        skip,
        take: limit,
      });

      const totalPages = Math.ceil(total / limit);

      return {
        data,
        total,
        page,
        limit,
        totalPages,
      };
    } catch (error) {
      this.logger.error('Error fetching recipes', error);
      throw error;
    }
  }

  /**
   * Creates a new recipe with automatic embedding generation for RAG search
   * @param name - Recipe name
   * @param ingredients - List of ingredients
   * @param instructions - Cooking instructions
   * @returns The created recipe ID (UUID)
   */
  public async createRecipe(
    name: string,
    ingredients: string,
    instructions: string,
  ): Promise<string> {
    try {
      // Generate embedding for the ingredients using RAG service
      const embedding = await this.ragService.getQueryEmbedding(ingredients);
      const embeddingString = `[${embedding.join(',')}]`;

      // Insert recipe with embedding (UUID will be auto-generated by database)
      const result = (await this.dataSource.query(
        `
        INSERT INTO recipes (name, ingredients, instructions, embedding)
        VALUES ($1, $2, $3, $4::vector)
        RETURNING id
      `,
        [name, ingredients, instructions, embeddingString],
      )) as unknown as Array<{ id: string }>;

      const recipeId = result[0]?.id;
      this.logger.log(`Recipe "${name}" created with ID: ${recipeId}`);
      return recipeId;
    } catch (error) {
      this.logger.error('Error creating recipe', error);
      throw error;
    }
  }
}
