import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository, InjectDataSource } from '@nestjs/typeorm';
import { DifficultyLevel, Instrument } from '../entities/instrument.entity';
import { Repository, Like, DataSource } from 'typeorm';
import { GetInstrumentsQueryDto } from './dto/get-instruments-query.dto';
import { Pagination } from '../common/interfaces/pagination.interface';
import { RagService } from '../rag/rag.service';
import { CreateInstrumentDto } from './dto/create-instrument.dto';

@Injectable()
export class InstrumentsService {
  private readonly logger = new Logger(InstrumentsService.name);

  constructor(
    @InjectRepository(Instrument)
    private instrumentRepository: Repository<Instrument>,
    @InjectDataSource()
    private dataSource: DataSource,
    private ragService: RagService,
  ) {}

  /**
   * Gets all instruments from the database with optional filtering and pagination
   */
  public async getInstruments(
    query: GetInstrumentsQueryDto,
  ): Promise<Pagination<Instrument>> {
    try {
      const {
        search,
        instrument_family,
        difficulty_level,
        weight_category,
        volume_profile,
        airflow_requirement,
        embouchure_difficulty,
        recommended_beginners,
        page = 1,
        limit = 10,
      } = query;
      const skip = (page - 1) * limit;

      // Build where clause
      const where: Record<string, unknown> = {};
      if (search) {
        where.name = Like(`%${search}%`);
      }
      if (instrument_family) {
        where.instrument_family = instrument_family;
      }
      if (difficulty_level) {
        where.difficulty_level = difficulty_level;
      }
      if (weight_category) {
        where.weight_category = weight_category;
      }
      if (volume_profile) {
        where.volume_profile = volume_profile;
      }
      if (airflow_requirement) {
        where.airflow_requirement = airflow_requirement;
      }
      if (embouchure_difficulty) {
        where.embouchure_difficulty = embouchure_difficulty;
      }
      if (recommended_beginners !== undefined) {
        where.recommended_beginners = recommended_beginners;
      }

      // Get total count for pagination
      const total = await this.instrumentRepository.count({ where });

      // Get paginated results
      const data = await this.instrumentRepository.find({
        where,
        order: {
          created_at: 'DESC',
        },
        skip,
        take: limit,
      });

      const totalPages = Math.ceil(total / limit);

      return {
        data,
        total,
        page,
        limit,
        totalPages,
      };
    } catch (error) {
      this.logger.error('Error fetching instruments', error);
      throw error;
    }
  }

  /**
   * Gets instruments recommended for beginners
   */
  public async getRecommendedForBeginners(): Promise<Instrument[]> {
    try {
      return await this.instrumentRepository.find({
        where: {
          recommended_beginners: true,
          difficulty_level: DifficultyLevel.BEGINNER,
        },
        order: {
          name: 'ASC',
        },
      });
    } catch (error) {
      this.logger.error('Error fetching recommended instruments', error);
      throw error;
    }
  }

  /**
   * Creates a new instrument with automatic embedding generation for RAG search
   */
  public async createInstrument(
    createInstrumentDto: CreateInstrumentDto,
  ): Promise<string> {
    try {
      const {
        name,
        instrument_family,
        difficulty_level,
        weight_category,
        volume_profile,
        airflow_requirement,
        embouchure_difficulty,
        typical_price_min,
        typical_price_max,
        description,
        recommended_beginners,
      } = createInstrumentDto;

      // Generate embedding for the instrument description using RAG service
      // Combine name, family, and description for better semantic search
      const embeddingText = [
        name,
        description || '',
        `Instrument family: ${instrument_family}`,
        `Difficulty: ${difficulty_level}`,
        `Weight: ${weight_category}`,
        `Volume: ${volume_profile}`,
        `Airflow: ${airflow_requirement}`,
        `Embouchure: ${embouchure_difficulty}`,
      ].join(' ');

      const embedding = await this.ragService.getQueryEmbedding(embeddingText);
      const embeddingString = `[${embedding.join(',')}]`;

      // Insert instrument with embedding (UUID will be auto-generated by database)
      const result = (await this.dataSource.query(
        `
        INSERT INTO instruments (
          name, instrument_family, difficulty_level, weight_category, volume_profile,
          airflow_requirement, embouchure_difficulty, typical_price_min,
          typical_price_max, description, recommended_beginners, embedding
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::vector)
        RETURNING id
      `,
        [
          name,
          instrument_family,
          difficulty_level,
          weight_category,
          volume_profile,
          airflow_requirement,
          embouchure_difficulty,
          typical_price_min,
          typical_price_max,
          description || null,
          recommended_beginners,
          embeddingString,
        ],
      )) as unknown as Array<{ id: string }>;

      const instrumentId = result[0]?.id;
      this.logger.log(`Instrument "${name}" created with ID: ${instrumentId}`);
      return instrumentId;
    } catch (error) {
      this.logger.error('Error creating instrument', error);
      throw error;
    }
  }

  /**
   * Gets a single instrument by ID
   */
  public async getInstrumentById(instrumentId: string): Promise<Instrument> {
    try {
      const instrument = await this.instrumentRepository.findOne({
        where: { id: instrumentId },
      });

      if (!instrument) {
        throw new Error(`Instrument with ID ${instrumentId} not found`);
      }

      return instrument;
    } catch (error) {
      this.logger.error(`Error fetching instrument ${instrumentId}`, error);
      throw error;
    }
  }
}
